import { IEvent } from "../../../API/Events/IEvent";
import { IEventProvider } from "../def/IEventProvider";

const events: IEvent[] = [
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "1",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "2",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "3",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "4",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "5",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "6",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "7",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "8",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "9",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "10",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "11",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "12",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "13",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "14",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "15",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "16",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "17",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "18",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "19",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "20",
  },
];

export class MockEventProvider implements IEventProvider {
  ProvideEvents(page: number, limit: number) {
    // return events[0*15] + 15;
  } 
}
