import { IEvent } from "../../../API/Events/IEvent";
import { IEventProvider } from "../def/IEventProvider";

const events: IEvent[] = [
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "1",
    featured: false,
    name: "ASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "2",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "3",
    featured: false,
    name: "casdf",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "4",
    featured: false,
    name: "ASDFASDFasfdgsdfg",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "5",
    featured: false,
    name: ";lgksjdfg;ljk",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "6",
    featured: false,
    name: "ghjsadf",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "7",
    featured: false,
    name: "caleb",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "8",
    featured: false,
    name: "test",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "9",
    featured: false,
    name: "yoyo",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "10",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "11",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "12",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "13",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "14",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "15",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "16",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "17",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "18",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "19",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "20",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "1",
    featured: false,
    name: "ASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "2",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "3",
    featured: false,
    name: "casdf",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "4",
    featured: false,
    name: "ASDFASDFasfdgsdfg",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "5",
    featured: false,
    name: ";lgksjdfg;ljk",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "6",
    featured: false,
    name: "ghjsadf",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "7",
    featured: false,
    name: "caleb",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "8",
    featured: false,
    name: "test",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "9",
    featured: false,
    name: "yoyo",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "10",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "11",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "12",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "13",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "14",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "15",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "16",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "17",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "18",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "19",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "20",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "1",
    featured: false,
    name: "ASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "2",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "3",
    featured: false,
    name: "casdf",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "4",
    featured: false,
    name: "ASDFASDFasfdgsdfg",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "5",
    featured: false,
    name: ";lgksjdfg;ljk",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "6",
    featured: false,
    name: "ghjsadf",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "7",
    featured: false,
    name: "caleb",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "8",
    featured: false,
    name: "test",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "9",
    featured: false,
    name: "yoyo",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "10",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "11",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "12",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "13",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "14",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "15",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "16",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "17",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "18",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "19",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "20",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "1",
    featured: false,
    name: "ASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "2",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "3",
    featured: false,
    name: "casdf",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "4",
    featured: false,
    name: "ASDFASDFasfdgsdfg",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "5",
    featured: false,
    name: ";lgksjdfg;ljk",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "6",
    featured: false,
    name: "ghjsadf",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "7",
    featured: false,
    name: "caleb",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "8",
    featured: false,
    name: "test",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "9",
    featured: false,
    name: "yoyo",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "10",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "11",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "12",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "13",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "14",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "15",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "16",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "17",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "18",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "19",
    featured: false,
    name: "ASDFASDF",
  },
  {
    end_timestamp: new Date(),
    start_timestamp: new Date(),
    title: "Asdf",
    user_id: "1",
    category_id: "1",
    description: "1",
    event_id: "20",
    featured: false,
    name: "ASDFASDF",
  },
];

export class MockEventProvider implements IEventProvider {
  async ProvideEvents(page: number, limit: number) {
    return events.slice(page, limit);
  }
}
